// <auto-generated />
using System;
using SaigonAudioTour.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SaigonAudioTour.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260312070053_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaigonAudioTour.Api.Entities.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("POIId")
                        .HasColumnType("int");

                    b.Property<int>("POI_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("POIId");

                    b.ToTable("Audios");
                });

            modelBuilder.Entity("SaigonAudioTour.Api.Entities.Narration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("POIId")
                        .HasColumnType("int");

                    b.Property<int>("POI_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("POIId");

                    b.ToTable("Narrations");
                });

            modelBuilder.Entity("SaigonAudioTour.Api.Entities.POI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Radius")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("POIs");
                });

            modelBuilder.Entity("SaigonAudioTour.Api.Entities.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("SaigonAudioTour.Api.Entities.TourPOI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("POI_Id")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("POI_Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourPOIs");
                });

            modelBuilder.Entity("SaigonAudioTour.Api.Entities.UserLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<int?>("POIId")
                        .HasColumnType("int");

                    b.Property<int?>("POI_Id")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("POIId");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("SaigonAudioTour.Api.Entities.Audio", b =>
                {
                    b.HasOne("SaigonAudioTour.Api.Entities.POI", "POI")
                        .WithMany("Audios")
                        .HasForeignKey("POIId");

                    b.Navigation("POI");
                });

            modelBuilder.Entity("SaigonAudioTour.Api.Entities.Narration", b =>
                {
                    b.HasOne("SaigonAudioTour.Api.Entities.POI", "POI")
                        .WithMany("Narrations")
                        .HasForeignKey("POIId");

                    b.Navigation("POI");
                });

            modelBuilder.Entity("SaigonAudioTour.Api.Entities.TourPOI", b =>
                {
                    b.HasOne("SaigonAudioTour.Api.Entities.POI", "POI")
                        .WithMany("TourPOIs")
                        .HasForeignKey("POI_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaigonAudioTour.Api.Entities.Tour", "Tour")
                        .WithMany("TourPOIs")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("POI");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("SaigonAudioTour.Api.Entities.UserLog", b =>
                {
                    b.HasOne("SaigonAudioTour.Api.Entities.POI", "POI")
                        .WithMany()
                        .HasForeignKey("POIId");

                    b.Navigation("POI");
                });

            modelBuilder.Entity("SaigonAudioTour.Api.Entities.POI", b =>
                {
                    b.Navigation("Audios");

                    b.Navigation("Narrations");

                    b.Navigation("TourPOIs");
                });

            modelBuilder.Entity("SaigonAudioTour.Api.Entities.Tour", b =>
                {
                    b.Navigation("TourPOIs");
                });
#pragma warning restore 612, 618
        }
    }
}
